### ISSUE TITLE
"Open Dashboard/API Browser" not working when packaged with PyInstaller

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-qt#20]
When running aw-qt, the "Open Dashboard" and "Open API Browser" buttons fail to open the browser. When running aw-qt from source on the latest master it works fine though. 

This part seems to be the cause

```
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
```

Here are the full logs

```
Opening dashboard
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
/usr/bin/xdg-open: line 854: x-www-browser: command not found
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
/usr/bin/xdg-open: line 854: iceweasel: command not found
/usr/bin/xdg-open: line 854: seamonkey: command not found
/usr/bin/xdg-open: line 854: mozilla: command not found
/usr/bin/xdg-open: line 854: epiphany: command not found
/usr/bin/xdg-open: line 854: konqueror: command not found
/usr/bin/xdg-open: line 854: chromium: command not found
/usr/bin/xdg-open: line 854: chromium-browser: command not found
/usr/bin/xdg-open: line 854: google-chrome: command not found
/usr/bin/xdg-open: line 854: www-browser: command not found
/usr/bin/xdg-open: line 854: links2: command not found
/usr/bin/xdg-open: line 854: elinks: command not found
/usr/bin/xdg-open: line 854: links: command not found
/usr/bin/xdg-open: line 854: lynx: command not found
/usr/bin/xdg-open: line 854: w3m: command not found
xdg-open: no method available for opening 'http://localhost:5600'
```

```
Opening api browser
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
/usr/bin/xdg-open: line 854: x-www-browser: command not found
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
/usr/bin/xdg-open: line 854: iceweasel: command not found
/usr/bin/xdg-open: line 854: seamonkey: command not found
/usr/bin/xdg-open: line 854: mozilla: command not found
/usr/bin/xdg-open: line 854: epiphany: command not found
/usr/bin/xdg-open: line 854: konqueror: command not found
/usr/bin/xdg-open: line 854: chromium: command not found
/usr/bin/xdg-open: line 854: chromium-browser: command not found
/usr/bin/xdg-open: line 854: google-chrome: command not found
/usr/bin/xdg-open: line 854: www-browser: command not found
/usr/bin/xdg-open: line 854: links2: command not found
/usr/bin/xdg-open: line 854: elinks: command not found
/usr/bin/xdg-open: line 854: links: command not found
/usr/bin/xdg-open: line 854: lynx: command not found
/usr/bin/xdg-open: line 854: w3m: command not found
xdg-open: no method available for opening 'http://localhost:5600/api'
```

**Comment by ErikBjare** [comment]
Hmm, so looks like it tries to use the bundled libstdc++ instead of the system libstdc++ when starting firefox. Perhaps we should use something else than the `webbrowser` module in the standard library.

**Comment by ErikBjare** [comment]
Just tried it with the v0.7.0b2 build, seems to work fine now.

**Comment by johan-bjareholt** [comment]
Just downloaded 0.7.0b2, still the same issue and exactly the same logs sadly.

**Comment by ErikBjare** [comment]
Hmm... Can you try setting chrome as your default browser and see what happens?

**Comment by johan-bjareholt** [comment]
Seems to be other errors in that case.

```
Opening dashboard
/opt/google/chrome/google-chrome: /home/johan/Downloads/activitywatch/libdbus-1.so.3: no version information available (required by /usr/lib/libgconf-2.so.4)
/opt/google/chrome/google-chrome: /home/johan/Downloads/activitywatch/libdbus-1.so.3: no version information available (required by /usr/lib/libdbus-glib-1.so.2)
/opt/google/chrome/chrome: /home/johan/Downloads/activitywatch/libdbus-1.so.3: no version information available (required by /usr/lib/libgconf-2.so.4)
/opt/google/chrome/chrome: /home/johan/Downloads/activitywatch/libdbus-1.so.3: no version information available (required by /usr/lib/libdbus-glib-1.so.2)
/opt/google/chrome/chrome http://localhost:5600: symbol lookup error: /usr/lib/libgtk-x11-2.0.so.0: undefined symbol: g_type_check_instance_is_fundamentally_a
/usr/bin/xdg-open: line 854: x-www-browser: command not found
/usr/lib/firefox/firefox: /home/johan/Downloads/activitywatch/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/firefox/firefox)
/usr/bin/xdg-open: line 854: iceweasel: command not found
/usr/bin/xdg-open: line 854: seamonkey: command not found
/usr/bin/xdg-open: line 854: mozilla: command not found
/usr/bin/xdg-open: line 854: epiphany: command not found
/usr/bin/xdg-open: line 854: konqueror: command not found
/usr/bin/xdg-open: line 854: chromium: command not found
/usr/bin/xdg-open: line 854: chromium-browser: command not found
/usr/bin/xdg-open: line 854: google-chrome: command not found
/usr/bin/xdg-open: line 854: www-browser: command not found
/usr/bin/xdg-open: line 854: links2: command not found
/usr/bin/xdg-open: line 854: elinks: command not found
/usr/bin/xdg-open: line 854: links: command not found
/usr/bin/xdg-open: line 854: lynx: command not found
/usr/bin/xdg-open: line 854: w3m: command not found
xdg-open: no method available for opening 'http://localhost:5600'
```

**Comment by johan-bjareholt** [comment]
@lundibundi Yeah, the state of the PyInstaller release bundles aren't great but there are sadly no good alternatives. For Linux I will likely make an attempt to make a flatpak package later which should solve these issues there at least. For now the recommended installation method on linux is from source which should be stable.

> First of all both buttons produce fontconfig parsing error with various fields in the default config reported as errors (this is probably due to the new format of fontconfig 2.13+ as I understood after a bit of googling and it seems that AW bundles older fontconfig library which is not compatible with the new config)

Ugly hack, but could possibly be fixed by removing "libfontconfig.so.1" in the activitywatch folder.

**Comment by lundibundi** [comment]
@johan-bjareholt well, I've just tried that. aw-qt segfaulted right away =)
As for the source install I'll try that, thanks.

**Comment by xylix** [comment]
Is this a non-issue now that we build the bundle in ActivityWatch/activitywatch and it has working dashboard / api broswer buttons?

**Comment by ErikBjare** [comment]
The bundle has always been built in ActivityWatch/activitywatch. This particular issue only ever happened in some Linux environments, and I'm not exactly what those were so can't be sure if it's still an issue. But works fine for me on Arch Linux.

**Comment by tuxitop** [comment]
This is an annoying bug which is apparently still present in arch linux. I have been able to work around this for now by using running the following command to start `aw-qt`.

`LD_PRELOAD="/usr/lib/libstdc++.so.6 /usr/lib/libfreetype.so.6 /usr/lib/libz.so.1" aw-qt`

**Comment by Rapiz1** [comment]
I think it's not difficult to write a wrapper for `webbrowser` and use `xdg-open` for Linux. What do you think of this solution? @ErikBjare

**Comment by johan-bjareholt** [comment]
Someone who has this issue, could you try this out if it works?
https://github.com/ActivityWatch/aw-qt/pull/59#issuecomment-649280546

**Comment by johan-bjareholt** [comment]
It is now merged, will be fixed in the next version of ActivityWatch or if you build yourself from master.

If it doesn't work for someone, please add a comment and I'll reopen this issue.
